### ISSUE TITLE
Check if every badge_*.c component handles pre-init keypresses well.

### ISSUE THREAD

**Issue by basvs** [SHA2017-badge/Firmware#146]
Just fixed the mpr121 implementation, but probably want to check and fix the others as well.

**Comment by annejan** [comment]
I have tested all the features I could think about . . 
None seem to be affected . . 

Keeping a button pressed to get to the function you want (start from splash) feels very nice!

**Comment by basvs** [comment]
issue should be fixed for all badges after merging #181
