### ISSUE TITLE
building on OSX

### ISSUE THREAD

**Issue by nlitsme** [SHA2017-badge/Firmware#184]
The toolchain from the [xtensa-esp32-elf](https://github.com/SHA2017-badge/xtensa-esp32-elf) repository is for Linux only.

If you want to build on a mac, do the following:

* download the [mac toolchain](https://dl.espressif.com/dl/xtensa-esp32-elf-osx-1.22.0-61-gab8375a-5.2.0.tar.gz) from [this page](https://dl.espressif.com/doc/esp-idf/latest/get-started/macos-setup.html)
* rename the linux toolchain: `mv xtensa-esp32-elf xtensa-esp32-elf-linux`
* untar the mac toolchain: ` tar zxf ~/Downloads/xtensa-esp32-elf-osx-1.22.0-61-gab8375a-5.2.0.tar.gz`
* install the `CP2102` [usbserial driver](https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers)

* then in the `sdkconfig` file change this line:
    CONFIG_ESPTOOLPY_PORT="/dev/tty.SLAB_USBtoUART"

**Comment by Roosted7** [comment]
Could you make a pr and update the readme? :+1:

**Comment by basvs** [comment]
@annejan iirc you use osx as well. can you help out? :)

**Comment by nlitsme** [comment]
here is my pull request: https://github.com/SHA2017-badge/Firmware/pull/202
