### ISSUE TITLE
SDCard Support

### ISSUE THREAD

**Issue by ripper121** [SHA2017-badge/Firmware#196]
Why is there no SDCard Support?
>>> import machine, sdcard, os
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'sdcard'

**Comment by basvs** [comment]
there is sdcard support, but maybe not in a micropython way.

try 'badge.mount_sdcard()' and the sdcard is mounted as /sdcard.
(this folder is not visible unless you create it first with uos.mkdir('/sdcard') before mounting)
