### ISSUE TITLE
sha2017_ota.c: out-of-bounds read in sha2017_read_past_http_header

### ISSUE THREAD

**Issue by pesco** [SHA2017-badge/Firmware#200]
the line

      ptr = memchr(text + i, '\n', total_len);

  will access memory after the `text` buffer as `i` is incremented but 
 `total_len` stays constant. the loop will only terminate when it hits an area
  of memory of size `total_len` that incidentally contains no newline.

**Comment by basvs** [comment]
The ota code was buggy and completely unreadable; tried to make it bug-free and readable again:

https://github.com/SHA2017-badge/Firmware/pull/205

**Comment by basvs** [comment]
@pesco This file has largely been rewritten. Can I close this issue?

**Comment by pesco** [comment]
If the code in question no longer exists, sure.
