### ISSUE TITLE
Support for both RGB and RGBW SK6812

### ISSUE THREAD

**Issue by lkarlslund** [SHA2017-badge/Firmware#53]
It would be really nice with build in support for both types of LEDs. They seem to be able to be combined on one length of string, so you could - in theory - extend the onboard 6 RGBW LEDs with some RGB LEDs after that.

Example at https://github.com/sonyhome/FAB_LED#soldering-ws2812b--sk6812-rgbw

**Comment by annejan** [comment]
Yes.. https://wiki.sha2017.org/w/Projects:Badge/MicroPython#import_badge
```
badge.leds_send_data(grbw_values, length)
```
The grbw_values can also be mixed RGB GRBW or what-ever LED type you use.

Make sure to add 4 bytes for RGBW and 3 for RGB, length should just be the length in bytes of the values. .   

So we should have you sorted, we'll give this a try over the weekend to be sure it works!
