### ISSUE TITLE
Make sure the WS2812_DATA is in high-impedance mode before the LED power is switched off

### ISSUE THREAD

**Issue by annejan** [SHA2017-badge/Firmware#59]
It might break 📟

**Comment by basvs** [comment]
on disabling the power to the ws2812/sk6812, i can disable the spi and configure the gpio pin as input without pull-up or pull-down. i think that qualifies as high-impedance.

should i do this right before or right after disabling power?

**Comment by niekproductions** [comment]
Probably before disabling power, otherwise the sk6812's input capacitance can drain into the ESP and damage its I/O

**Comment by basvs** [comment]
Oh, and can someone with SK6812RGBW leds test the leds demo? It should start with these 6 leds: red, green, blue, white, black, black..

**Comment by annejan** [comment]
I'll test when I get home..

**Comment by annejan** [comment]
And . . it's Green, Red, Blue, Black, Black

**Comment by basvs** [comment]
Added pull-request #62

**Comment by basvs** [comment]
sprite_tm: is this the best way to put a GPIO pin in high-impedance?

**Comment by Spritetm** [comment]
There isn't really a 'the best way'; this one should do just fine.
