### ISSUE TITLE
Mass-flashing script

### ISSUE THREAD

**Issue by raboof** [SHA2017-badge/Firmware#68]
Should detect a badge being connected to one of the USB ports and flash it.

Should support flashing multiple badges in parallel.

**Comment by Roosted7** [comment]
Should preferably detect CP2102/4 version and flash at highest baud rate (1M/2M)

**Comment by basvs** [comment]
I've created a new repository for auto-flashing. That tool does handle multiple USB ports.

It currently always uses +- 1 MB bps rate. It's fast enough for now..
