### ISSUE TITLE
Question: New distribution technique

### ISSUE THREAD

**Issue by slaff** [SHA2017-badge/Firmware#8]
In [this post](https://sha2017.org/blog/talk-announcement-the-sha2017-badge-the-badge-is-a-go) you are mentioning 

> Featuring a brand new distribution technique designed by Sprite_TM, we can update badges without associating to the WiFi access points.

Can describe with technical details what is meant here?

**Comment by annejan** [comment]
This is the bpp update protocol suite hackery thingamajig. It's essentially a protocol encapsulating
multiple streams, sent over UDP over a WiFi network, so clients can pick it up and decode it without
having to connect to the network or transmit anything.


https://github.com/SHA2017-badge/bpp

**Comment by slaff** [comment]
@annejan Thanks a lot!
