### ISSUE TITLE
mpr121 Left and A sometimes 'hang'

### ISSUE THREAD

**Issue by annejan** [SHA2017-badge/Firmware#80]
Both in C Demo FW as in MicroPython ugfx.

**Comment by basvs** [comment]
The touch base-line is currently "a guess". We could add a calibrate option for better handling.

What we also could try is change the RELEASE value for all buttons. This can be found in badge_mpr121.c on line 215:

>         badge_mpr121_write_reg(MPR121_RELEASETH_0 + 2*i,  6); // release

Does it help if you increase the '6'?
